[tools]
jq = "latest"

node = "{{ exec(command='jq -r .engines.node package.json') | default(value='lts') }}"
uv = "latest"

awscli = "latest"

# Node.js global packages
"npm:openupm-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@upstash/context7-mcp" = "latest"
